#pragma once

#include <QtGlobal>

#if defined(QTCREATORDISCORDRICHPRESENCE_LIBRARY)
#  define QTCREATORDISCORDRICHPRESENCESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTCREATORDISCORDRICHPRESENCESHARED_EXPORT Q_DECL_IMPORT
#endif
